spring:
  multipart:
    max-file-size: 5
    max-request-size: 5
  mvc:
    servlet:
      path: /api/v1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  scheduling:
    thread-name-prefix: scheduler-
    pool:
      size: 10
    shutdown:
      await-termination: true
      await-termination-period: 30
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      security.protocol: PLAINTEXT
      spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432

kafka:
  topic:
    post-viewed-event:
      name: "post-viewed-event"
      partition: 1
      replicationFactor: 1
    comments:
      name: "comments"
      partition: 1
      replicationFactor: 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel

server:
  port: 8081

logging:
  level:
    root: info

user-service:
  host: localhost
  port: 8080/api/v1
project-service:
  host: localhost
  port: 8082
payment-service:
  host: localhost
  port: 9080

image:
  processing:
    max-file-size-mb: 5
    max-count-per-post: 10
    resize:
      horizontal:
        width: 1080
        height: 566
      square:
        width: 1080
        height: 1080
    allowed-content-types:
      - image/jpeg
      - image/png

post-service:
  tag:
    count-of-most-popular-tags: 2
  post:
    count-of-unverified-posts-to-ban: 5
  redis:
    ban-user-key: user_ban

app:
  scheduling:
    daily-midnight-cron: "0 0 0 * * ?" # Every day at 00:00
    daily-one-am-cron: "0 0 1 * * ?" # Every day at 01:00
    post:
      max-posts-per-time: 10
  dictionary:
    post-dictionary-path: /dictionary/post-forbidden-words.txt
  cache:
    authors:
      ttl: 86400 #24 hours
      key-prefix: "post-authors"
    posts:
      ttl: 86400
      key-prefix: "posts"
      value: "views"
    consumer:
      group-id: post-view-consumers

s3:
  endpoint: http://localhost:9000
  accessKey: user
  secretKey: password
  bucketName: corpbucket

image-s3:
  resize-sizes:
    - 1080
    - 170